### ISSUE TITLE
老兄能不能搞个建表语句出来，想学习一下

### ISSUE THREAD

**Issue by JamesxuWang** [1181649328/Blog#2]
建表语句

**Comment by JamesxuWang** [comment]
为公司开发一个后端管理系统（四）里面的图片也坏掉了

**Comment by 1181649328** [comment]
非常抱歉，才看到你的issues。图片缺失是因为我更换了域名和服务器，我正在修改。至于建表语句的话。需要交流可以联系我的企鹅1181649328.

**Comment by 1181649328** [comment]
> 为公司开发一个临时管理系统（四）里面的图片也坏掉了

非常抱歉，才看到你的消息。图片缺失是因为我更换了域名和服务器,导致url失效，如果想获得较好的浏览体验访问这个域名就能看到图片了，blog5.net.cn。至于建表语句的话。需要交流可以联系我的企鹅1181649328

**Comment by ZhouMo-O** [comment]
> 为公司开发一个临时管理系统（四）里面的图片也坏掉了



> 建表语句
哥们，你好，我新版本博客的基本功能已经制作完成了，你是第一个和我互动的人，所有先请你看 www.blog5.net.cn

**Comment by JamesxuWang** [comment]
恭喜恭喜哈哈哈
